backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Path", name: "slug", widget: "slug" }
  - name: "ﾃ始trebﾄビi frecvente"
    label: "ﾃ始trebﾄビi frecvente"
    folder: "content/intrebari-frecvente"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Path", name: "slug", widget: "string" }
